package hr.ferit.josipnedic.f1racecalendar.Racing

import hr.ferit.josipnedic.f1racecalendar.R

val races = listOf(
    F1Race(
        id = 1,
        image=R.drawable.bahrein,
        layout = R.drawable.bahreinlay,
        name = "Formula 1 Gulf air Bahrain Grand Prix",
        date ="February 29.",
        location = "Bahrain",
        training1Time = "February 29. 12:30 Friday",
        training2Time = "February 29. 16:00 Friday",
        training3Time = "March 1. 13:30 Saturday",
        qualyTime ="March 1. 17:00 Saturday",
        raceTime = "March 2. 16:00 Sunday"
    ),
    F1Race(
        id = 2,
        image=R.drawable.saudi,
        layout = R.drawable.saudilay,
        name = "Formula 1 STC Saudi Arabian Grand Prix",
        date ="March 7.",
        location = "Saudi Arabia",
        training1Time = "March 7. 14:30 Friday",
        training2Time = "March 7. 18:00 Friday",
        training3Time = "March 8. 14:30 Saturday",
        qualyTime = "March 8. 18:00 Saturday",
        raceTime = "March 9. 18:00 Sunday"
),
    F1Race(
        id = 3,
        image=R.drawable.australia,
        layout = R.drawable.australialay,
        name = "Formula 1 Rolex Australian Grand Prix",
        date ="March 22.",
        location = "Australia",
        training1Time = "March 22. 2:30 Friday",
        training2Time = "March 22. 6:00 Friday",
        training3Time = "March 23. 2:30 Saturday",
        qualyTime = "March 23. 6:00 Saturday",
        raceTime = "March 22. 5:00 Sunday"
    ),
    F1Race(
        image=R.drawable.japan,
        layout = R.drawable.japanlay,
        id = 4,
        name = "Formula 1 MSC cruises Japanese Grand Prix",
        date ="April 5.",
        location = "Japan",
        training1Time = "April 5. 4:30 Friday",
        training2Time = "April 5. 8:00 Friday",
        training3Time = "April 6. 4:30 Saturday",
        qualyTime = "April 6. 8:00 Saturday",
        raceTime = "April 7. 7:00 Sunday"
    ),
    F1Race(
        image=R.drawable.kina,
        layout = R.drawable.chinalay,
        id = 5,
        name = "Formula 1 Lenovo Chinese Grand Prix",
        date ="April 19.",
        location = "China",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.miami,
        layout = R.drawable.miamilay,
        id = 6,
        name = "Formula 1 Crypto.com Miami Grand Prix",
        date ="May 3.",
        location = "United States",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.imola,
        layout = R.drawable.imolalay,
        id = 7,
        name = "Formula 1 MSC cruises Gran Premio Delle'Emilia-Romagna",
        date ="May 17.",
        location = "Italy",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.monaco,
        layout = R.drawable.monacolay,
        id = 8,
        name = "Formula 1 Grand Prix De Monaco",
        date ="May 24.",
        location = "Monaco",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.canada,
        layout = R.drawable.canadalay,
        id = 9,
        name = "Formula 1 Grand Prix Du Canada",
        date ="June 7.",
        location = "Canada",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.spain,
        layout = R.drawable.spainlay,
        id = 10,
        name = "Formula 1 Aramco Gran Premio De España",
        date ="June 21.",
        location = "Spain",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.austria,
        layout = R.drawable.australialay,
        id = 11,
        name = "Formula 1 Qatar Airways Austrian Grand Prix",
        date ="June 28.",
        location = "Austria",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.greatbritain,
        layout = R.drawable.greatbritainlay,
        id = 12,
        name = "Formula 1 Qatar Airways British Grand Prix",
        date ="July 5.",
        location = "Great Britain",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.hungary,
        layout = R.drawable.hungarylay,
        id = 13,
        name = "Formula 1 Hungarian Grand Prix",
        date ="July 19.",
        location = "Hungary",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.belgium,
        layout = R.drawable.belgiumlay,
        id = 14,
        name = "Formula 1 Rolex Belgian Grand Prix",
        date ="July 26.",
        location = "Belgium",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.netherlands,
        layout = R.drawable.netherlands,
        id = 15,
        name = "Formula 1 Heineken Dutch Grand Prix",
        date ="August 23.",
        location = "Netherlands",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.monza,
        layout = R.drawable.monzalay,
        id = 16,
        name = "Formula 1 Pirelli Gran Premio D'Italia",
        date ="August 30.",
        location = "Italy",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.azerbaijan,
        layout = R.drawable.azerbaijanlay,
        id = 17,
        name = "Formula 1 Qatar Airways Azerbaijan Grand Prix",
        date ="September 13.",
        location = "Azerbaijan",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.singapore,
        layout = R.drawable.singapore,
        id = 18,
        name = "Formula 1 Singapore Airlines Singapore Grand Prix",
        date ="September 22.",
        location = "Singapore",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.usa,
        layout = R.drawable.usalay,
        id = 19,
        name = "Formula 1 Pirelli United States Grand Prix",
        date ="October 18.",
        location = "United States",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.mexico,
        layout = R.drawable.mexicolay,
        id = 20,
        name = "Formula 1 Gran Premio De La Ciudad De Mexico",
        date ="October 25.",
        location = "Mexico",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.brazil,
        layout = R.drawable.brazillay,
        id = 21,
        name = "Formula 1 Lenovo Grande Premio De Sao Paulo",
        date ="November 1.",
        location = "Brazil",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.lasvegas,
        layout = R.drawable.lasvegaslay,
        id = 22,
        name = "Formula 1 Heineken Silver Las Vegas Grand Prix",
        date ="November 21.",
        location = "United States",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.qatar,
        layout = R.drawable.qatarlay,
        id = 23,
        name = "Formula 1 Qatar Airways Qatar Grand Prix",
        date ="November 29.",
        location = "Qatar",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    ),
    F1Race(
        image=R.drawable.abudhabi,
        layout = R.drawable.abudhabilay,
        id = 24,
        name = "Formula 1 Etihad Airways Abu Dhabi Grand Prix",
        date ="December 6.",
        location = "Abu Dhabi",
        training1Time = "TBC",
        training2Time = "TBC",
        training3Time = "TBC",
        qualyTime = "TBC",
        raceTime = "TBC"
    )
)


